podTemplate(yaml: '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: git
    image: bitnami/git:latest
    command:
    - sleep
    args:
    - infinity
''') {
    node(POD_LABEL) {
       checkout scm
       if( buildingTag() ){
           checkout scm
           echo 'Generando nueva release de los datos'
           echo 'Nos aseguramos de tener en local la rama develop'
           echo 'Cambiamos a master'
           sh 'git checkout master'
           sh 'git pull master'
           echo 'Llevamos lo último de develop'
           sh 'git merge develop'
           //sh 'git push'
           //sh 'git push tags'
       }
       
    }
}
